# Generated by Django 4.1.4 on 2022-12-22 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, max_length=150, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='head_image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(choices=[('Bishkek', 'Bishkek'), ('Karakol', 'Karakol'), ('Cholpon-ata', 'Cholpon-ata')], default='city-1', max_length=50),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(default=None, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, max_length=150, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='advertisement.category')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='advertisement.advertisement')),
                ('promotion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advertisement_promotion', to='advertisement.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('body', models.TextField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='advertisement.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advertisement', to='advertisement.subcategory'),
            preserve_default=False,
        ),
    ]
