# Generated by Django 4.1.4 on 2023-01-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='slug',
        ),
    ]
