# Generated by Django 4.1.4 on 2022-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
