# Generated by Django 3.2.7 on 2021-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisementimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adImages/%advertisement.username/%Y/%m/%d'),
        ),
    ]
