# Generated by Django 4.1.4 on 2023-01-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_remove_advertisement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='contacts',
        ),
        migrations.AddField(
            model_name='advertisementpromotion',
            name='advertisement',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.PROTECT, related_name='promotion', to='advertisement.advertisement'),
            preserve_default=False,
        ),
    ]
