# Generated by Django 4.1.4 on 2023-01-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_advertisement_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementcomment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='advertisementcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_comment', to='advertisement.advertisementcomment'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisementcomment',
            name='body',
            field=models.TextField(max_length=5000),
        ),
    ]
