# Generated by Django 3.2.7 on 2021-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar/Billy.jpg', null=True, upload_to='avatar/'),
        ),
    ]
